apiVersion: v1
kind: ServiceAccount
metadata:
  name: dask-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dask-controller
rules:
  - {apiGroups: [""], resources: ["pods", "services"], verbs: ["*"]}
  - {apiGroups: ["apps"], resources: ["deployments"], verbs: ["*"]}
  - {apiGroups: ["dask.charmtx.com"], resources: ["clusters", "clusters/status", "clusters/scale"], verbs: ["*"]}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dask-controller
roleRef:
  {apiGroup: "rbac.authorization.k8s.io", kind: ClusterRole, name: dask-controller}
subjects:
  - {kind: ServiceAccount, name: dask-controller}
